### PR TITLE
Require InstantaneousPowerProperty for SmartPlug.

### PR DESCRIPTION
**Pull request by mrstegeman**

### CODE REVIEW

**Comment by benfrancis** [comment]
My only concern with making the InstantaneousPowerProperty mandatory is that there are some smart plugs that don't offer that feature, or we don't yet expose it. You could argue the additional semantic information alone that this on/off switch is actually smart plug would be enough to justify differentiating it. Like how we might show a different UI for an OnOffProperty to a BooleanProperty even though they're both just boolean values. The user might want to save it as a smart plug, even if it doesn't report power usage. Also a smart plug can have a LevelProperty but an OnOffSwitch can not.

I take your point that the UI currently depends on this property, but that's really an implementation detail due to our current UI design.

**Comment by mrstegeman** [comment]
@benfrancis That's definitely a fair point. We'll just need to update our UI component.

**Comment by benfrancis** [comment]
So what would we need to change in the UI? Maybe the smart plug icon can be smart enough to just display "ON" rather than the current power usage if power usage isn't provided?

**Comment by mrstegeman** [comment]
Yes, I had planned on doing that today. It should be very straightforward.

Unrelated, but should a light switch say it has a `Light` capability, or should that one stay as just an `OnOffSwitch`? I could kind of see it both ways.

**Pull request closed without merging**
