### PR TITLE
Add MediaPlayer capability

### PR DESCRIPTION
**Pull request by mrstegeman**
Rebase of #5

### CODE REVIEW

**Comment by mrstegeman** [comment]
@freaktechnik Sorry, I messed up trying to rebase and ended up closing your PR as a result.

**Comment by freaktechnik** [comment]
No problem, thank you for rebasing it. The thought had crossed my mind just an hour or so ago...

I have a couple of updates I want to propose:
- Make PlayingProperty optionally read-only if a device only supports stopping. In that case starting playback would likely have to be done via an action too, and else I guess the play property would just have really weird behavior to start with.
- The PreviewURLProperty should be updated to essentially be an ImageProperty
- An optional MutedProperty may make sense for nice muting UI, since muting and pausing aren't the same, especially for visual media
- The ProgressProperty in its current form isn't entirely usable, since the maximum progress available is not really dynamic with the current schema behavior.
- Optimally the metadata properties (Track, Artist, Album, PreviewURL) would be a prop collection/object but that's not yet a thing ;)

**Comment by freaktechnik** [comment]
And to add to the ProgressProperty, some devices may have a fast forward/backward instead because they do not know their relative position within the medium.

**Comment by mrstegeman** [comment]
If it would be easier, you can submit a PR to my branch and we can do things that way.

**Comment by freaktechnik** [comment]
Alright, PR submitted for the things that I have a clear opinion about.

**Pull request closed without merging**
